### PR TITLE
fix display of gitter chat badge

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
The current markup doesn't display correctly on github, possibly due to the [recent changes in markdown processing](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown).

**Comment by cmllr** [comment]
Thank you very much for your contribution!

**Comment by waldyrious** [comment]
@cmllr my pleasure :) thank you for this awesome tool!

**Comment by cmllr** [comment]
Glad you like the distrochooser :)

**Pull request merged**
